spring:
  datasource:
        url: jdbc:mysql://localhost:3306/coder_hub?useSSL=false&useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

server:
      port: 8080
      address: localhost
##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
